
# The default Mint category.
DEFAULT_MINT_CATEGORY = 'Shopping'

# The default return category.
DEFAULT_MINT_RETURN_CATEGORY = 'Returned Purchase'

# A category mapping of Amazon Order History "Categories" into Mint
# "Categories".
AMAZON_TO_MINT_CATEGORY = {
    'Accessory': DEFAULT_MINT_CATEGORY,
    'Apparel': 'Clothing',
    'Audio CD': 'Music',
    'Automotive': 'Auto & Transport',
    'Baby Product': 'Baby Supplies',
    'Blu-ray': 'Movies & DVDs',
    'CD-ROM': 'Music',
    'Camera': 'Electronics & Software',
    'Electronics': 'Electronics & Software',
    'Eyewear': 'Eyecare',
    'Grocery': 'Groceries',
    'Hardcover': 'Books',
    'Health and Beauty': 'Personal Care',
    'Home': 'Home',
    'Kitchen': DEFAULT_MINT_CATEGORY,
    'Lawn & Patio': 'Lawn & Garden',
    'Luggage': DEFAULT_MINT_CATEGORY,
    'Mass Market Paperback': 'Books',
    'Misc.': DEFAULT_MINT_CATEGORY,
    'Office Product': 'Office Supplies',
    'Paperback': 'Books',
    'Personal Computers': 'Electronics & Software',
    'Print on Demand': DEFAULT_MINT_CATEGORY,
    'Shoes': 'Clothing',
    'Software Download': 'Electronics & Software',
    'Sports': 'Sporting Goods',
    'Sports Apparel': 'Sporting Goods',
    'T-shirt': 'Clothing',
    'Tools & Hardware': 'Home',
    'Tools & Home Improvement': 'Home Improvement',
    'Toy': 'Toys',
    'Video Game': 'Electronics & Software',
    'Watch': DEFAULT_MINT_CATEGORY,
    'Wine': 'Alcohol & Bars',
    'Wireless Phone Accessory': 'Electronics & Software',
}

MINT_CATEGORIES = set([
    'Income',
    'Paycheck',
    'Investment',
    'Returned Purchase',
    'Bonus',
    'Interest Income',
    'Reimbursement',
    'Rental Income',
    'Misc',
    'Uncategorized'
    'Cash & ATM',
    'Check',
    'Exclude From Mint',
    'Entertainment',
    'Arts',
    'Music',
    'Movies & DVDs',
    'Newspaper & Magazines',
    'Education',
    'Tuition',
    'Student Loan',
    'Books & Supplies',
    'Shopping',
    'Clothing',
    'Books',
    'Electronics & Software',
    'Hobbies',
    'Sporting Goods',
    'Personal Care',
    'Laundry',
    'Hair',
    'Spa & Massage',
    'Remove: Sports',
    'Health & Fitness'
    'Dentist',
    'Doctor',
    'Eye care',
    'Pharmacy',
    'Health Insurance',
    'Gym',
    'Sports',
    'Kids',
    'Activities',
    'Allowance',
    'Baby Supplies',
    'Babysitter & Daycare',
    'Child Support',
    'Toys',
    'Food & Dining',
    'Groceries',
    'Coffee shops',
    'Fast Food',
    'Restaurants',
    'Alcohol',
    'Gifts & Donations',
    'Gift',
    'Charity',
    'Investments',
    'Deposit',
    'Withdrawal',
    'Dividends & Cap Gains',
    'Buy',
    'Sell',
    'Bills & Utilities',
    'Television',
    'Home Phone',
    'Internet',
    'Mobile Phone',
    'Utilities',
    'Auto & Transport',
    'Gas & Fuel',
    'Parking',
    'Service & Auto Parts',
    'Auto Payment',
    'Auto Insurance',
    'Service & Auto Parts',
    'Travel',
    'Air Travel',
    'Hotel',
    'Rental Car & Taxi',
    'Vacation',
    'Fees & Charges',
    'Service Fee',
    'Late Fee',
    'Finance Charge',
    'ATM Fee',
    'Bank Fee',
    'Commissions',
    'Business Services',
    'Advertising',
    'Office Supplies',
    'Printing',
    'Shipping',
    'Legal',
    'Taxes',
    'Federal Tax',
    'State Tax',
    'Local Tax',
    'Sales Tax',
    'Property Tax',
])
